### ISSUE TITLE
No links in graph view

### ISSUE THREAD

**Issue by mrmagic113** [auroral-ui/aurora-obsidian-md#2]
Have an issue where the links aren't appearing in graph view. I have tried increasing their thickness but that doesn't seem to be doing anything. Have attached an image of what this looks like.
![Capture](https://user-images.githubusercontent.com/82960850/115581406-9a9b1f80-a2e5-11eb-9f0f-e0739d021753.PNG)

**Comment by bennyxguo** [comment]
@mrmagic113 I couldn't reproduce this issue, could it be that you have some other CSS snippets turned on?

**Comment by stalegjelsten** [comment]
@mrmagic113 , I also cant't see any links in graph view before hovering the links. I tried creating a fresh vault with no plugins other than Aurora theme. See attached GIF 👇

![Skjermopptak 2021-12-25 kl  12 30 19](https://user-images.githubusercontent.com/5513050/147384051-f0a13bae-213e-4b06-83af-4c2e7fb9b401.gif)

I added graph links by adding the following to the CSS file:
```css
.graph-view.color-line {
  color: var(--interactive-accent);
}
.graph-view.color-line-highlight { 
  color: var(--interactive-accent-hover);
}
```

Which looks like this 👇 
<img width="974" alt="bilde" src="https://user-images.githubusercontent.com/5513050/147384137-9301ad54-7bfb-457b-9175-681cb587fbe1.png">
