### ISSUE TITLE
Can't see horizontal rule

### ISSUE THREAD

**Issue by Dowsley** [auroral-ui/aurora-obsidian-md#8]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/22419861/211364955-ac37a4c9-9efa-4d59-b231-fb444f81f1fa.png">

Rendered:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/22419861/211365017-034f71fc-9796-4c3e-a9a1-35c7fe5f7090.png">

**Comment by Dowsley** [comment]
Temporary fix with

```css
.markdown-preview-view hr, hr {
	border-color: var(--interactive-accent);
}
```
